Lab Activity #2: Question 3 

#### 1. Import the numpy package under the name `np` 

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [24]:
import numpy as np 
np.__version__

'2.5.1'

#### 3. Create a null vector of size 10 

In [2]:
import numpy as np
vector=np.zeros(10)
np.array(vector)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [3]:
np.size(vector)

10

#### 5. Create a null vector of size 10 but the fifth value which is 1 

In [18]:
null_vector=np.zeros(10)
null_vector
null_vector[4:9:5]=1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 

In [10]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) 

In [12]:
np.flip(np.arange(10,50))

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 

In [22]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [ ]:
np.array([1,2,0,0,4,0])



#### 10. Create a 3x3 identity matrix 

In [25]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values 

In [33]:
np.random.rand(27).reshape(3,3,3)

array([[[0.37336108, 0.85425067, 0.06999868],
        [0.19816907, 0.71163651, 0.55291   ],
        [0.67884215, 0.69216034, 0.1724899 ]],

       [[0.92775625, 0.35881723, 0.37323226],
        [0.00449648, 0.30902026, 0.68295002],
        [0.66243921, 0.16910197, 0.14719909]],

       [[0.11029568, 0.61224704, 0.01436176],
        [0.32190062, 0.8093506 , 0.04155503],
        [0.70160488, 0.29788059, 0.78110711]]])

#### 12. Create a 10x10 array with random values and find the minimum and maximum values 

In [39]:
random_arr=np.random.rand(100).reshape(10,10)
print(random_arr)
print("min = ", np.min(random_arr))
print("max = ", np.max(random_arr))


[[0.6474691  0.3032882  0.8269792  0.63900456 0.68331917 0.20058335
  0.14198153 0.58115684 0.36285578 0.02658997]
 [0.00759944 0.95881011 0.65812647 0.64802863 0.84110938 0.23913768
  0.70796909 0.83579682 0.14844729 0.26124333]
 [0.50822787 0.86138991 0.88693961 0.78656825 0.25276178 0.06077844
  0.09815111 0.16986671 0.98792202 0.6918403 ]
 [0.04447738 0.86871438 0.43799485 0.50422406 0.9165297  0.54761285
  0.36275304 0.10652773 0.0662574  0.85254073]
 [0.47639201 0.29127658 0.91739996 0.92621738 0.44870646 0.59411911
  0.00796228 0.67703475 0.63803343 0.74608149]
 [0.51716108 0.43290932 0.29147448 0.62294351 0.57686631 0.54165026
  0.97550886 0.61871902 0.5435893  0.16902991]
 [0.89284774 0.28058642 0.90613244 0.99705412 0.51479485 0.22011207
  0.46218597 0.99082966 0.87838378 0.11659264]
 [0.25235887 0.75901504 0.30055579 0.09609796 0.1612171  0.78245783
  0.67284649 0.23213963 0.62578336 0.31627761]
 [0.63336138 0.86737343 0.17315806 0.47082214 0.83102997 0.90486684
  0.00678532

#### 13. Create a random vector of size 30 and find the mean value 

In [42]:
vector_30 = np.random.rand(30)
print(vector_30)
print("mean = ", np.mean(vector_30))

[0.6428408  0.73046383 0.04593022 0.52945312 0.09650878 0.26062373
 0.1995311  0.51344648 0.39073496 0.30701737 0.13873362 0.54875099
 0.09449195 0.979785   0.02476175 0.76813171 0.12316044 0.46330266
 0.47646898 0.23691884 0.65229007 0.43192254 0.60551808 0.95639365
 0.28189871 0.59078967 0.13122101 0.9885242  0.36532318 0.15275233]
mean =  0.42425632560253684


#### 14. Create a 2d array with 1 on the border and 0 inside 

In [1]:
import numpy as np

arr = np.zeros((5, 5), dtype=int)

arr[0, :] = 1      # top
arr[-1, :] = 1     # bottom
arr[:, 0] = 1      # left
arr[:, -1] = 1     # right

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [10]:
import numpy as np
x=0*np.nan
print(x)
np.nan==np.nan    #FALSE
np.inf>np.nan     #FALSE
np.nan-np.nan     #nan
np.nan in set([np.nan])  #TRUE
0.3 == 3 * 0.1  #FALSE


nan


False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [11]:
arr = np.zeros((5, 5), dtype=int)
arr[1, 0] = 1
arr[2, 1] = 2
arr[3, 2] = 3
arr[4, 3] = 4
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [12]:
import numpy as np

arr = np.zeros((6, 7, 8))

index = np.unravel_index(99, arr.shape)

print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 18. Normalize a 5x5 random matrix 

In [13]:
import numpy as np

# Create 5x5 random matrix
arr = np.random.rand(5, 5) * 100

print("Original Matrix:")
print(arr)

# Min-Max normalization
normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("\nNormalized Matrix:")
print(normalized)

Original Matrix:
[[86.04546814 82.22469544 82.86639833 43.88078282 57.13849337]
 [15.49272751 53.62291112  6.42966182 80.54838448 64.12148931]
 [40.88486108 31.24022828 83.72645524 23.48856698 33.41479103]
 [32.10834522 27.73488712 33.57058314 40.09975299 53.1129782 ]
 [38.10961943 86.42202427 13.75609981 27.43018748 79.20961491]]

Normalized Matrix:
[[0.9952926  0.94752838 0.95555043 0.46818371 0.63392091]
 [0.11329914 0.58997194 0.         0.92657249 0.7212167 ]
 [0.43073111 0.31016169 0.96630217 0.21325667 0.33734632]
 [0.32101419 0.26634074 0.33929391 0.42091632 0.58359717]
 [0.39603728 1.         0.09158922 0.26253163 0.90983628]]


#### 19. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [14]:
import numpy as np

A = np.random.randint(1, 10, (5, 3))
B = np.random.randint(1, 10, (3, 2))

C = np.dot(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nResult:")
print(C)

Matrix A:
[[3 8 6]
 [9 2 3]
 [5 2 3]
 [5 4 7]
 [3 7 1]]

Matrix B:
[[1 8]
 [1 3]
 [3 6]]

Result:
[[29 84]
 [20 96]
 [16 64]
 [30 94]
 [13 51]]


#### 20. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [15]:
import numpy as np

arr = np.array([1, 3, 5, 7, 9, 4, 10, 8])

arr[(arr >= 3) & (arr <= 8)] *= -1

print(arr)

[ 1 -3 -5 -7  9 -4 10 -8]
