In [1]:
import numpy as np

data = np.array([10, 25, 40, 15, 60, 5])

# 1. Generate a boolean mask
mask = data > 20
print(mask)
# array([False,  True,  True, False,  True, False])

# 2. Filter elements matching the condition
filtered = data[data > 20]
print(filtered)
# Output: array([25, 40, 60])

[False  True  True False  True False]
[25 40 60]


In [2]:
arr = np.array([10, 20, 30, 40, 50])

indices = [0, 2, 4]
selected = arr[indices]
print(selected)
# Output: array([10, 30, 50])

[10 30 50]
