In [9]:
# Vector
import numpy as np
arr = np.arange(25)
arr.shape

(25,)

In [5]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# Notice the two sets of brackets
new=arr.reshape(1,25)
new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [2]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [6]:
s=np.zeros(20)
np.reshape(s,(4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
arr = np.arange(0,1000)

#Show
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [25]:
slice_of_arr = arr[0:999:2]
slice_of_arr[:] = 5
arr

array([  5,   1,   5,   3,   5,   5,   5,   7,   5,   9,   5,  11,   5,
        13,   5,  15,   5,  17,   5,  19,   5,  21,   5,  23,   5,  25,
         5,  27,   5,  29,   5,  31,   5,  33,   5,  35,   5,  37,   5,
        39,   5,  41,   5,  43,   5,  45,   5,  47,   5,  49,   5,  51,
         5,  53,   5,  55,   5,  57,   5,  59,   5,  61,   5,  63,   5,
        65,   5,  67,   5,  69,   5,  71,   5,  73,   5,  75,   5,  77,
         5,  79,   5,  81,   5,  83,   5,  85,   5,  87,   5,  89,   5,
        91,   5,  93,   5,  95,   5,  97,   5,  99,   5, 101,   5, 103,
         5, 105,   5, 107,   5, 109,   5, 111,   5, 113,   5, 115,   5,
       117,   5, 119,   5, 121,   5, 123,   5, 125,   5, 127,   5, 129,
         5, 131,   5, 133,   5, 135,   5, 137,   5, 139,   5, 141,   5,
       143,   5, 145,   5, 147,   5, 149,   5, 151,   5, 153,   5, 155,
         5, 157,   5, 159,   5, 161,   5, 163,   5, 165,   5, 167,   5,
       169,   5, 171,   5, 173,   5, 175,   5, 177,   5, 179,   

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([35,40,50,55,65])
m,c=np.polyfit(x,y,1)
print("slope = ",m)
print("intercept = ",c)



slope =  7.500000000000002
intercept =  26.49999999999997


In [5]:
import numpy as np

# Given data
x = np.array([1, 2, 3, 4, 5])
slope = 7.500000000000002
intercept = 27.500000000000007

y_actual = np.array([35, 40, 50, 55, 65])
# Predicted values using vectorised multiplication
y_pred = slope * x + intercept
print("Predicted values:", y_pred)



Predicted values: [35.  42.5 50.  57.5 65. ]


In [3]:
# Error
error = y_actual - y_pred
print("Error:", error)
# Absolute Error
absolute_error = np.abs(error)
print("Absolute Error:", absolute_error)

Error: [-7.10542736e-15 -2.50000000e+00 -1.42108547e-14 -2.50000000e+00
 -1.42108547e-14]
Absolute Error: [7.10542736e-15 2.50000000e+00 1.42108547e-14 2.50000000e+00
 1.42108547e-14]


In [4]:
# Mean Square Error
mse = np.mean(error * error)
print("Mean Square Error:", mse)

Mean Square Error: 2.5000000000000284
